### ISSUE TITLE
Grpc.Core.RpcException

### ISSUE THREAD

**Issue by J-Holloway** [zaront/vector#3]
Hello, Great work it's amazing
how ever after a while of playing about with some concepts I started getting the following error and could not find anything on google. 

'Status(StatusCode=ResourceExhausted, Detail="Maximum auth rate exceeded. Please wait and try again later.")'

Is there somewhere I can read up about this? and how did I likely cause the issue?

Thanks

**Comment by zaront** [comment]
You aren't, by chance, calling GrantApiAccessAsync in your code are you?  I
have seen "ResourceExhausted" if you have called that method a bunch of
times.  If you are, its because that method should only be called one time
and then your good for a year.  After that you never need to call it again
in your code, instead you just call the ConnectAsync to connect, forever in
the future.  If that was your case, the reason for ResourceExhausted
exception its that it is sent from Anki's cloud authorization service to
throttle unnecessary and excessive calls to their service.

If this wasn't the case for you, send me your code causing the issue and
I'll take a look.

**Comment by J-Holloway** [comment]
Hi, Sorry I am not with the code at the moment but I am pretty sure that I am calling GrantApiAccessAsync  every time i was running the code, i will amend this and retest as soon as possible 

Thank you :)

**Comment by J-Holloway** [comment]
Yes that was the issue thank you,

**Comment by zaront** [comment]
Awesome.  Glad it's working for you now
